### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by johntdavis84** [MatthewVance/unbound-docker-rpi#18] opened 2021-07-20 14:14 UTC
Hello!

My apologies in advance for what is most likely a profoundly stupid question. ;)

I just installed an updated image this morning. Is there a changeling somewhere?

**Comment by MatthewVance** [comment] 2021-07-20 14:26
No, there's not. Only Git history. Periodically, I'll push a new build as
latest without code changes. It is to pull in an updated base image and
refresh apt get packages.

**Comment by MatthewVance** [comment] 2021-07-30 01:40
Duplicate of https://github.com/MatthewVance/unbound-docker-rpi/issues/11

**Closed by MatthewVance** 2021-07-30 01:40 UTC
Labels: duplicate
